import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
import { FruitMergeModel, FRUITS, WIDTH, HEIGHT, DANGER_Y } from './fruit-merge-model.js';

const TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const ease=t=>t*t*(3-2*t);
const BEST_KEY='jelly-room.fruit-merge.best.v1';
const COLORS=['#b80d3d','#dc2742','#61349e','#edc626','#ed8011','#c42b29','#90aa2b','#ed7672','#cb930a','#87a82e','#d92145'];
const SVG={back:'<path d="m14 5-7 7 7 7M7 12h13"/>',pause:'<path d="M8 5v14M16 5v14"/>',play:'<path d="m8 4 12 8-12 8Z"/>',restart:'<path d="M4 10a8 8 0 1 1 0 5M4 4v6h6"/>',left:'<path d="m14 5-7 7 7 7M7 12h12"/>',right:'<path d="m10 5 7 7-7 7M17 12H5"/>',drop:'<path d="M12 3v15m-6-6 6 6 6-6M5 22h14"/>',sound:'<path d="m11 5-5 4H3v6h3l5 4ZM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',mute:'<path d="m11 5-5 4H3v6h3l5 4ZM16 9l6 6m0-6-6 6"/>'};
const svg=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${SVG[name]||SVG.play}</svg>`;
const number=value=>Math.floor(value||0).toLocaleString('zh-CN');
function best(){try{return clamp(Number(localStorage.getItem(BEST_KEY))||0,0,1e12);}catch{return 0;}}

// These are fruit cross sections rather than emoji, so the growing collection stays legible everywhere.
function icon(level,id='fruit'){
 const color=COLORS[level]||COLORS[0],gradient=`fm-${id}-${level}`;
 const outer=level===10?'<circle cx="32" cy="35" r="26" fill="#356d3f"/><circle cx="32" cy="35" r="23" fill="#acd25e"/><circle cx="32" cy="35" r="20" fill="url(#G)"/>':level===6?'<path d="M32 8c-9 0-8 15-15 22C3 45 10 60 32 60s29-15 15-30C40 23 41 8 32 8Z" fill="url(#G)"/>':level===1?'<path d="M10 24C7 9 22 7 32 12c10-5 25-3 22 12-3 16-14 32-22 36-8-4-19-20-22-36Z" fill="url(#G)"/>':level===3?'<path d="M7 34c2-22 45-28 50-2 3 24-43 30-50 2Z" fill="url(#G)"/>':level===8?'<ellipse cx="32" cy="38" rx="22" ry="25" fill="url(#G)"/>':level===7?'<path d="M32 17C8-1-7 48 19 58c8 3 18 3 26-1C71 43 51 0 32 17Z" fill="url(#G)"/>':'<circle cx="32" cy="36" r="25" fill="url(#G)"/>';
 let detail='';
 if(level===1)for(let i=0;i<13;i++){const y=20+(i%4)*8,x=21+((i*13)%25);detail+=`<ellipse cx="${x}" cy="${y}" rx="1.2" ry="2.2" fill="#ffe1a0" transform="rotate(${i%2?18:-18} ${x} ${y})"/>`;}
 if(level===10)for(let i=0;i<7;i++){const a=i*2.3,x=32+Math.cos(a)*(i%2?9:14),y=35+Math.sin(a)*(i%2?9:14);detail+=`<ellipse cx="${x}" cy="${y}" rx="1.8" ry="3.1" fill="#4b252d" transform="rotate(${i*37} ${x} ${y})"/>`;}
 if(level===8)detail+='<path d="m13 25 34 29M10 38l29 24M19 17l33 30M50 25 13 29M54 38 25 24M44 17 11 30" stroke="#8c6207" stroke-width="1" opacity=".5"/>';
 if(level===9)detail+='<path d="M17 15Q10 36 17 57M29 11Q22 35 29 61M41 13Q48 35 41 59M51 19Q57 36 51 53" stroke="#bdc464" stroke-width="1" opacity=".65"/>';
 if(level===7)detail+='<path d="M32 18Q25 34 31 49" stroke="#bd4052" stroke-width="1.5" fill="none" opacity=".6"/>';
 if(level===8)detail+='<path d="M31 19 15 2l16 8L34 0l5 12 14-9-11 18Z" fill="#4f7943"/>';
 else if(level!==3&&level!==9&&level!==10)detail+='<path d="M32 14Q31 8 34 3" stroke="#705039" stroke-width="3" fill="none"/><path d="M34 10Q47-1 52 7 47 17 34 10Z" fill="#568044"/>';
 return `<svg class="fm-fruit-icon" viewBox="0 0 64 66" aria-hidden="true"><defs><radialGradient id="${gradient}" cx=".3" cy=".2" r=".85"><stop offset="0" stop-color="${color}" stop-opacity=".65"/><stop offset=".36" stop-color="${color}"/><stop offset="1" stop-color="${color}"/></radialGradient></defs><ellipse cx="33" cy="61" rx="19" ry="3" fill="#536342" opacity=".1"/>${outer.replaceAll('#G',`#${gradient}`)}${detail}<path d="M16 29Q17 19 25 19" fill="none" stroke="#fff9df" stroke-width="3" stroke-linecap="round" opacity=".58"/></svg>`;
}

/** A 2D fruit garden with genuinely deforming 3D skins. The host owns its animation frame. */
export class FruitMergeGame{
 constructor({onExit=()=>{},onSound=()=>{}}={}){
  this.onExit=onExit;this.onSound=onSound;this._visible=false;this.soundEnabled=true;this.bestScore=best();this.sessionBest=this.bestScore;
  this.renderer=null;this.visuals=new Map();this.ghosts=[];this.particles=[];this.fusions=[];this.heldInputs=new Map();this.pointerCaptures=new Map();this.activePointers=new Set();this.gesture=null;this.cancelledGesture=false;
  this.time=0;this.frames=0;this.eventLog=[];this._hudKey='';this._overlayStatus='';this._lastContactSound=-10;this._toastUntil=0;this._maxIndent=0;this._deformPoint=new THREE.Vector3();this.reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
  this.root=document.createElement('section');this.root.id='fruit-merge-screen';this.root.hidden=true;this.root.setAttribute('aria-label','水果果冻合成游戏');
  this.root.innerHTML=`<header class="fm-topbar"><button id="fm-exit" class="fm-back" data-fm-action="exit">${svg('back')}<span>返回小店</span></button><div class="fm-wordmark"><i>j.</i><span>JELLY ROOM</span><small>FRUIT GARDEN / 03</small></div><div class="fm-top-actions"><button id="fm-sound" data-fm-action="sound" aria-label="关闭水果果冻声音" title="声音 · M">${svg('sound')}</button><button id="fm-pause" data-fm-action="pause" aria-label="暂停游戏" title="暂停 · P / Esc">${svg('pause')}</button><button id="fm-restart-top" data-fm-action="restart" aria-label="重新开局">${svg('restart')}</button></div></header>
   <main class="fm-layout"><aside class="fm-left"><div class="fm-heading"><span>A LITTLE GARDEN OF JELLY</span><h1>软软大西瓜<span>。</span></h1><p>碰一碰，<br>长成更大的甜。</p></div><section class="fm-score-card" aria-label="分数"><span class="fm-label">这一篮的甜 / SCORE</span><strong id="fm-score">0</strong><div class="fm-best"><span>最好的一篮</span><b id="fm-best">0</b></div></section><div class="fm-next-card"><span class="fm-label">下一颗 <small>NEXT</small></span><div id="fm-next-icon"></div><span id="fm-next-name">草莓</span></div><div class="fm-goal"><span class="fm-label">今天的小目标</span><strong>养出一颗大西瓜</strong><div class="fm-goal-progress"><i id="fm-goal-bar"></i></div><small id="fm-goal-caption">从一颗樱桃开始。</small></div><p class="fm-keyboard"><span><kbd>← →</kbd> 调整位置</span><span><kbd>空格 / Enter</kbd> 轻轻放下</span><span><kbd>P / Esc</kbd> 暂停 · <kbd>M</kbd> 声音</span></p></aside>
   <div class="fm-stage"><canvas id="fm-canvas" tabindex="0" aria-label="三维果冻水果篮，左右移动选择落点，点击或松手放下水果，相同水果碰到后合成"></canvas><div id="fm-warning" class="fm-warning" role="status" aria-live="polite"><span>篮子快满啦</span><b id="fm-warning-time">3.0</b><small>快把上面的水果合起来</small></div><div class="fm-stage-note"><span id="fm-current-name">樱桃</span><i></i><span id="fm-drop-hint">按住移动 · 松手放下</span></div><div id="fm-merge-toast" class="fm-merge-toast" role="status" aria-live="polite"></div><div id="fm-overlay" class="fm-overlay"></div></div>
   <aside class="fm-right"><div class="fm-growth-title"><span>一颗颗，长大</span><small>THE FRUIT FAMILY</small></div><ol id="fm-family" class="fm-family">${FRUITS.map((fruit,level)=>`<li data-level="${level}" class="${level===10?'fm-family-goal':''}"><span class="fm-family-number">${String(level+1).padStart(2,'0')}</span>${icon(level,'family')}<span>${fruit.name}</span><i></i></li>`).join('')}</ol><p class="fm-soft-note">压下去，会软。<br>碰一起，会长大。</p></aside></main>
   <nav class="fm-touch-controls" aria-label="触控操作"><button id="fm-left" data-fm-control="left" aria-label="向左调整落点">${svg('left')}</button><button id="fm-drop" data-fm-control="drop">${svg('drop')}<span>轻轻放下</span><kbd>SPACE</kbd></button><button id="fm-right" data-fm-control="right" aria-label="向右调整落点">${svg('right')}</button></nav>`;
  document.body.append(this.root);this.canvas=this.root.querySelector('#fm-canvas');this.stage=this.root.querySelector('.fm-stage');
  this.model=new FruitMergeModel({onEvent:event=>this._onEvent(event)});this._bindInputs();this._updateHUD();this.resizeObserver=new ResizeObserver(()=>{if(this._visible)this.resize();});this.resizeObserver.observe(this.stage);
 }
 get active(){return this._visible;}
 get state(){
  const snapshot=this.model.snapshot(),r=this.canvas.getBoundingClientRect();
  const deformationBodies=[...this.visuals.values()].map(v=>({id:v.id,indent:Number((v.maxVertexDisplacement||0).toFixed(4)),wobble:Number(Math.abs(v.wobble).toFixed(4))}));
  return {...snapshot,activeMode:this._visible,bestScore:this.bestScore,soundEnabled:this.soundEnabled,heldInputs:[...this.heldInputs.keys()],render:{ready:!!this.renderer&&!this.renderError,frames:this.frames,fruits:this.visuals.size,particles:this.particles.length,fusions:this.fusions.length,width:this.canvas.width,height:this.canvas.height,deformations:deformationBodies.filter(v=>v.indent>.001).length,deformationBodies,maxIndent:this._maxIndent,drawCalls:this.renderer?.info.render.calls||0,projection:{left:r.left,top:r.top,width:r.width,height:r.height,zero:this.project(0,0),x10:this.project(WIDTH,0),y14:this.project(0,HEIGHT)}},lastEvents:this.eventLog.map(event=>({...event}))};
 }
 get debug(){return this.state;}
 project(x,y){if(!this.camera)return null;const p=new THREE.Vector3(x-WIDTH/2,y,0).project(this.camera),r=this.canvas.getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};}
 open(){this._visible=true;this.root.hidden=false;this._releaseInputs();if(!this.renderer&&!this.renderError)this._initRenderer();this.resize();this._overlayStatus='';this._updateHUD();this._syncVisuals();this._renderFrame(0);}
 close(){this._releaseInputs();if(this.model.status==='playing')this.model.pause();this._saveBest();this._visible=false;this.root.hidden=true;}
 resize(){
  if(!this.renderer||!this._visible)return;const r=this.stage.getBoundingClientRect();if(r.width<1||r.height<1)return;
  const width=Math.round(r.width),height=Math.round(r.height),ratio=Math.min(devicePixelRatio||1,1.65);if(this._width===width&&this._height===height&&this._ratio===ratio)return;this._width=width;this._height=height;this._ratio=ratio;this.renderer.setPixelRatio(ratio);this.renderer.setSize(width,height,false);
  const aspect=width/height,viewHeight=Math.max(15.6,11.7/aspect);this.camera.left=-viewHeight*aspect/2;this.camera.right=viewHeight*aspect/2;this.camera.top=viewHeight/2;this.camera.bottom=-viewHeight/2;this.camera.updateProjectionMatrix();
 }
 frame(dtSeconds){if(!this._visible)return;const dt=clamp(Number.isFinite(dtSeconds)?dtSeconds:0,0,.05);if(this.model.status==='playing'){this._repeatInputs(dt);this.model.tick(dt);}this._updateHUD();this._syncVisuals();this._renderFrame(this.model.status==='paused'?0:dt);}
 _sound(name,detail={}){if(this._visible&&this.soundEnabled)this.onSound(name,{intensity:1,...detail});}
 _saveBest(){if(this.model.score<=this.bestScore)return;this.bestScore=this.model.score;try{localStorage.setItem(BEST_KEY,String(this.bestScore));}catch{/* A browser that blocks storage can still play. */}}
 _start(){this._releaseInputs();this.sessionBest=this.bestScore;this._clearVisuals();this._toastUntil=0;this.root.querySelector('#fm-merge-toast').classList.remove('show');this.model.start();this._overlayStatus='';this._updateHUD();this._syncVisuals();this.canvas.focus({preventScroll:true});this._sound('start',{intensity:.7});}
 _togglePause(reason='manual'){this._releaseInputs();this.pauseReason=reason;if(this.model.status==='playing')this.model.pause();else if(this.model.status==='paused'){this.model.resume();this.canvas.focus({preventScroll:true});}this._updateHUD();}
 _autoPause(reason){if(!this._visible)return;this._releaseInputs();this.pauseReason=reason;if(this.model.status==='playing')this.model.pause();this._updateHUD();}
 _aim(clientX,clientY){if(!this.camera||this.model.status!=='playing')return;const r=this.canvas.getBoundingClientRect(),p=new THREE.Vector3((clientX-r.left)/r.width*2-1,1-(clientY-r.top)/r.height*2,.5).unproject(this.camera);const direction=this.camera.getWorldDirection(new THREE.Vector3());p.addScaledVector(direction,-p.z/direction.z);this.model.setAim(p.x+WIDTH/2);}
 _perform(action){if(this.model.status!=='playing')return;if(action==='drop'){this.model.drop();return;}this.model.setAim(this.model.aimX+(action==='left'?-.32:.32));}
 _bindInputs(){
  this.root.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled||!this._visible)return;const control=button.dataset.fmControl;if(control){if(event.detail===0)this._perform(control);return;}const action=button.dataset.fmAction;if(action==='start'||action==='restart')this._start();else if(action==='resume'&&this.model.status==='paused')this._togglePause();else if(action==='pause')this._togglePause();else if(action==='exit'){this.close();this.onExit();}else if(action==='sound'){this.soundEnabled=!this.soundEnabled;this._updateHUD();}});
  this.root.addEventListener('pointerdown',event=>{const control=event.target.closest('[data-fm-control]');if(!control||event.button!==0||!this._visible||this.model.status!=='playing')return;event.preventDefault();control.setPointerCapture(event.pointerId);this.pointerCaptures.set(event.pointerId,control);control.classList.add('pressed');if(control.dataset.fmControl==='drop')this._perform('drop');else this._press(control.dataset.fmControl,`pointer:${event.pointerId}`);});
  const releaseControl=event=>{this.pointerCaptures.delete(event.pointerId);this._releaseSource(`pointer:${event.pointerId}`);event.target.closest?.('[data-fm-control]')?.classList.remove('pressed');};
  this.root.addEventListener('pointerup',releaseControl);this.root.addEventListener('pointercancel',releaseControl);this.root.addEventListener('lostpointercapture',releaseControl);this.root.addEventListener('contextmenu',event=>event.preventDefault());
  this.canvas.addEventListener('pointerdown',event=>{if(!this._visible||this.model.status!=='playing'||event.button!==0)return;event.preventDefault();this.activePointers.add(event.pointerId);if(this.gesture||this.activePointers.size>1){this.gesture=null;this.cancelledGesture=true;return;}this.cancelledGesture=false;this._aim(event.clientX,event.clientY);this.gesture={id:event.pointerId};this.canvas.setPointerCapture(event.pointerId);this.pointerCaptures.set(event.pointerId,this.canvas);});
  this.canvas.addEventListener('pointermove',event=>{if(!this._visible||this.model.status!=='playing'||this.cancelledGesture)return;if(event.pointerType==='mouse'&&!this.gesture||this.gesture?.id===event.pointerId)this._aim(event.clientX,event.clientY);});
  const releaseGesture=event=>{this.activePointers.delete(event.pointerId);const gesture=this.gesture;if(gesture?.id===event.pointerId){this.gesture=null;if(event.type==='pointerup'&&!this.cancelledGesture&&this._visible&&this.model.status==='playing'){this._aim(event.clientX,event.clientY);this.model.drop();}}if(!this.activePointers.size)this.cancelledGesture=false;};
  this.canvas.addEventListener('pointerup',releaseGesture);this.canvas.addEventListener('pointercancel',releaseGesture);this.canvas.addEventListener('lostpointercapture',event=>{if(this.gesture?.id===event.pointerId)this.gesture=null;this.activePointers.delete(event.pointerId);});
  window.addEventListener('keydown',event=>{if(!this._visible)return;const key=event.code,keys=['ArrowLeft','ArrowRight','Space','Enter','KeyP','Escape','KeyM'];if(!keys.includes(key))return;if(['Space','Enter'].includes(key)&&event.target.closest?.('button'))return;event.preventDefault();event.stopImmediatePropagation();if(['KeyP','Escape'].includes(key)){if(!event.repeat)this._togglePause();return;}if(key==='KeyM'){if(!event.repeat){this.soundEnabled=!this.soundEnabled;this._updateHUD();}return;}if(this.model.status!=='playing')return;if(key==='ArrowLeft'||key==='ArrowRight'){if(!event.repeat)this._press(key==='ArrowLeft'?'left':'right',key);}else if(!event.repeat&&!this.heldInputs.has(key)){this.heldInputs.set(key,{sources:new Set([key])});this._perform('drop');}},true);
  window.addEventListener('keyup',event=>{if(!this._visible)return;if(['ArrowLeft','ArrowRight','Space','Enter','KeyP','Escape','KeyM'].includes(event.code)){event.preventDefault();event.stopImmediatePropagation();this._releaseSource(event.code);this.heldInputs.delete(event.code);}},true);
  window.addEventListener('blur',()=>this._autoPause('blur'));document.addEventListener('visibilitychange',()=>{if(document.hidden)this._autoPause('hidden');});
 }
 _press(action,source){if(this.model.status!=='playing')return;let held=this.heldInputs.get(action);if(!held){held={sources:new Set(),elapsed:0,next:.15};this.heldInputs.set(action,held);this._perform(action);}held.sources.add(source);}
 _releaseSource(source){for(const [action,held] of this.heldInputs){held.sources.delete(source);if(!held.sources.size)this.heldInputs.delete(action);}}
 _releaseInputs(){this.heldInputs.clear();this.gesture=null;this.activePointers.clear();this.cancelledGesture=false;for(const [id,element] of this.pointerCaptures){try{if(element.hasPointerCapture(id))element.releasePointerCapture(id);}catch{/* Pointer may already have been cancelled by the browser. */}}this.pointerCaptures.clear();this.root.querySelectorAll('[data-fm-control]').forEach(button=>button.classList.remove('pressed'));}
 _repeatInputs(dt){for(const [action,held] of this.heldInputs){if(!['left','right'].includes(action))continue;held.elapsed+=dt;let count=0;while(held.elapsed>=held.next&&count++<4){this._perform(action);held.next+=.045;}}}
 _onEvent(event){
  this.eventLog.push({type:event.type,level:event.level??event.body?.level,bodyId:event.bodyId??event.body?.id,scoreDelta:event.scoreDelta,chain:event.chain,intensity:event.intensity});if(this.eventLog.length>18)this.eventLog.shift();
  if(event.type==='reset')this._clearVisuals();
  if(event.type==='drop'){this._sound('drop',{level:event.body?.level,intensity:.6});if(this.preview)this.preview.kick=.12;}
  if(event.type==='contact'){
   for(const [id,sign] of [[event.bodyId,1],[event.otherId,-1]]){const visual=this.visuals.get(id);if(visual){const angle=Math.atan2(-event.ny*sign,-event.nx*sign)-visual.angle,index=((Math.round(angle/TAU*8)%8)+8)%8;visual.dents[index].velocity+=Math.min(4,(event.intensity||Math.min(1,(event.impactSpeed||event.impulse)/8))*3.2);visual.wobbleV+=Math.min(3,(event.intensity||.2)*2);}}
   if((event.impactSpeed||0)>1.1&&this.time-this._lastContactSound>.09){this._lastContactSound=this.time;this._sound('contact',{intensity:clamp(event.intensity||event.impactSpeed/10,.15,.7)});}
  }
  if(event.type==='merge'){
   if(this.renderer){const parents=event.parents||[];for(const parent of parents){const visual=this.visuals.get(parent.id);if(visual){this.visuals.delete(parent.id);this.fusions.push({visual,from:new THREE.Vector3(parent.x-WIDTH/2,parent.y,0),to:new THREE.Vector3(event.body.x-WIDTH/2,event.body.y,0),age:0,life:.25});}}
    const visual=this.visuals.get(event.body.id)||this._createVisual(event.body);visual.bornAt=this.time;visual.wobbleV=3.8;visual.formed=true;this._burst(event.body,event.level===10);
   }
   this._toastUntil=this.time+1.65;const toast=this.root.querySelector('#fm-merge-toast');toast.innerHTML=`<strong>${event.level===10?'一颗大西瓜，养成啦！':`${FRUITS[event.level].name}，长大了`}</strong><span>+${number(event.scoreDelta)}${event.chain>1?` · ${event.chain} 连合`:''}</span>`;toast.classList.add('show');this._sound(event.level===10?'watermelon':'merge',{level:event.level,intensity:event.level===10?1:.5+event.level*.035});
  }
  if(event.type==='gameover'||event.type==='over'){this._releaseInputs();this._sound('over',{intensity:.65});}
 }
 _updateHUD(){
  this._saveBest();const m=this.model,key=[m.score,m.highestLevel,m.watermelons,m.currentLevel,m.nextLevel,m.status,m.canDrop,this.bestScore,this.soundEnabled,this.renderError].join('|');
  if(key!==this._hudKey){this._hudKey=key;this.root.dataset.status=m.status;this.root.querySelector('#fm-score').textContent=number(m.score);this.root.querySelector('#fm-best').textContent=number(this.bestScore);this.root.querySelector('#fm-next-icon').innerHTML=icon(m.nextLevel??1,'next');this.root.querySelector('#fm-next-name').textContent=FRUITS[m.nextLevel??1].name;this.root.querySelector('#fm-current-name').textContent=FRUITS[m.currentLevel??0].name;this.root.querySelector('#fm-goal-bar').style.width=`${clamp(m.highestLevel||0,0,10)*10}%`;this.root.querySelector('#fm-goal-caption').textContent=m.watermelons?`已经养成 ${m.watermelons} 颗西瓜，继续收集甜。`:`已长到${FRUITS[m.highestLevel||0].name} · 还有 ${10-(m.highestLevel||0)} 次长大`;this.root.querySelectorAll('.fm-family li').forEach(li=>{li.classList.toggle('unlocked',Number(li.dataset.level)<=(m.highestLevel||0));li.classList.toggle('current',Number(li.dataset.level)===(m.highestLevel||0));});this.root.querySelector('#fm-pause').disabled=!['playing','paused'].includes(m.status);this.root.querySelector('#fm-pause').innerHTML=svg(m.status==='paused'?'play':'pause');this.root.querySelector('#fm-pause').setAttribute('aria-label',m.status==='paused'?'继续游戏':'暂停游戏');this.root.querySelector('#fm-drop').disabled=m.status!=='playing'||!m.canDrop;this.root.querySelector('#fm-left').disabled=m.status!=='playing';this.root.querySelector('#fm-right').disabled=m.status!=='playing';this.root.querySelector('#fm-sound').innerHTML=svg(this.soundEnabled?'sound':'mute');this.root.querySelector('#fm-sound').setAttribute('aria-label',this.soundEnabled?'关闭水果果冻声音':'开启水果果冻声音');this.root.querySelector('#fm-sound').setAttribute('aria-pressed',String(!this.soundEnabled));this.root.querySelector('#fm-drop-hint').textContent=m.status==='playing'&&!m.canDrop?'等它落稳一点':'按住移动 · 松手放下';}
  const warning=m.status==='playing'&&(m.overflowTime||0)>0;this.root.classList.toggle('fm-in-danger',warning);this.root.querySelector('#fm-warning').classList.toggle('show',warning);if(warning)this.root.querySelector('#fm-warning-time').textContent=Math.max(0,m.overflowRemaining||0).toFixed(1);
  const status=this.renderError?'error':m.status;if(status===this._overlayStatus)return;this._overlayStatus=status;const overlay=this.root.querySelector('#fm-overlay');overlay.hidden=status==='playing';if(status==='playing')return;let content;
  if(status==='ready')content=`<span class="fm-dialog-kicker">GROW A LITTLE SWEETNESS</span><h2>一碰，就甜到一起。</h2><p>把果冻水果轻轻放进篮子。<br>两颗一样的碰到一起，就会长大。</p><div class="fm-ready-family">${icon(0,'ready-a')}<span>＋</span>${icon(0,'ready-b')}<span>→</span>${icon(1,'ready-c')}</div><button id="fm-start" class="fm-primary" data-fm-action="start">开始养这一篮 ${svg('play')}</button><small class="fm-dialog-tip">鼠标 / 手指移动 · 松手放下 · 合出大西瓜</small>`;
  else if(status==='paused')content=`<span class="fm-dialog-kicker">YOUR FRUIT GARDEN CAN WAIT</span><h2>甜的，慢慢来。</h2><p>${['blur','hidden'].includes(this.pauseReason)?'离开画面时，已帮你暂停。':'这一篮水果好好地留在这里。'}<br>准备好了，再接着种。</p><button id="fm-resume" class="fm-primary" data-fm-action="resume">继续这一篮 ${svg('play')}</button><button id="fm-restart" class="fm-secondary" data-fm-action="restart">重新养一篮</button>`;
  else if(status==='error')content=`<span class="fm-dialog-kicker">A LITTLE PAUSE</span><h2>画面歇了一下。</h2><p>${this.renderError}</p><button class="fm-primary" data-fm-action="exit">回到小店 ${svg('back')}</button>`;
  else content=`<span class="fm-dialog-kicker">A BASKET FULL OF SWEET MOMENTS</span><h2>这一篮，收好啦。</h2><div class="fm-final-score">${number(m.score)}<span>本局得分${m.score>this.sessionBest?' · 新的最好成绩':''}</span></div><p>最大的甜：${FRUITS[m.highestLevel||0].name}<br>${m.watermelons?`养成 ${m.watermelons} 颗大西瓜`:`完成 ${m.merges||0} 次软软合成`}</p><button id="fm-restart" class="fm-primary" data-fm-action="restart">再养一篮 ${svg('restart')}</button><button class="fm-secondary" data-fm-action="exit">今天先收工</button>`;
  overlay.innerHTML=`<section class="fm-dialog" role="dialog" aria-modal="true" aria-label="${status==='ready'?'开始游戏':status==='paused'?'游戏暂停':status==='over'?'本局结束':'画面提示'}">${content}</section>`;if(this._visible)queueMicrotask(()=>overlay.querySelector('.fm-primary')?.focus({preventScroll:true}));
 }
 _initRenderer(){
  try{
   this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:true,powerPreference:'high-performance'});const renderer=this.renderer;renderer.setClearColor('#f1eedf',0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.94;
   this.scene=new THREE.Scene();this.camera=new THREE.OrthographicCamera(-7,7,8,-8,.1,100);this.camera.position.set(0,8.3,34);this.camera.lookAt(0,7.1,0);
   const room=new RoomEnvironment();const panel=new THREE.Mesh(new THREE.BoxGeometry(3,.1,2),new THREE.MeshBasicMaterial({color:new THREE.Color(2,2,2)}));panel.position.set(-3,4,0);room.add(panel);const pmrem=new THREE.PMREMGenerator(renderer);this.environment=pmrem.fromScene(room,.07);this.scene.environment=this.environment.texture;this.scene.environmentIntensity=.75;room.dispose();pmrem.dispose();
   this.scene.add(new THREE.HemisphereLight('#fff0da','#818468',1.0));const key=new THREE.DirectionalLight('#fff0ce',3.2);key.position.set(-8,19,14);key.target.position.set(0,5,0);key.castShadow=true;key.shadow.mapSize.set(1024,2048);Object.assign(key.shadow.camera,{left:-7,right:7,top:9,bottom:-9,near:.5,far:55});key.shadow.normalBias=.035;key.shadow.bias=-.0002;key.shadow.radius=3;this.scene.add(key,key.target);const fill=new THREE.DirectionalLight('#d8e8ff',1.0);fill.position.set(9,5,12);this.scene.add(fill);const rimLight=new THREE.DirectionalLight('#fff2cf',1.2);rimLight.position.set(-2,13,-5);this.scene.add(rimLight);
   this._createBasket();this.materials=FRUITS.map((fruit,level)=>this._createMaterial(level));this.stemMaterial=new THREE.MeshStandardMaterial({color:'#624635',roughness:.64});this.leafMaterial=new THREE.MeshPhysicalMaterial({color:'#3e7544',roughness:.43,clearcoat:.42,side:THREE.DoubleSide});this.seedMaterial=new THREE.MeshStandardMaterial({color:'#ffdfa0',roughness:.44});this.darkSeedMaterial=new THREE.MeshPhysicalMaterial({color:'#38212a',roughness:.24,clearcoat:.65});this.bubbleMaterial=new THREE.MeshPhysicalMaterial({color:'#fff9da',transparent:true,opacity:.24,roughness:.2,depthWrite:false});this.bubbleGeometry=new THREE.SphereGeometry(1,7,5);this.seedGeometry=new THREE.SphereGeometry(1,7,5);
   this.leafGeometry=this._leafGeometry();this.preview=this._createPreview();
  }catch(error){console.error('Fruit garden renderer',error);this.renderError='请使用支持 WebGL 2 的新版浏览器，并开启硬件加速。';this._overlayStatus='';this._updateHUD();}
 }
 _createBasket(){
  const ceramic=new THREE.MeshPhysicalMaterial({color:'#e4ead9',roughness:.38,clearcoat:.68});const plate=new THREE.Mesh(new RoundedBoxGeometry(10.85,12.3,.32,5,.42),new THREE.MeshStandardMaterial({color:'#e9eddc',roughness:.8}));plate.position.set(0,6.1,-2.72);plate.receiveShadow=true;this.scene.add(plate);
  const bottom=new THREE.Mesh(new RoundedBoxGeometry(11,.44,4.8,5,.21),ceramic);bottom.position.set(0,-.23,-.15);bottom.castShadow=true;bottom.receiveShadow=true;this.scene.add(bottom);
  const railMaterial=new THREE.MeshPhysicalMaterial({color:'#c1d4bc',roughness:.23,metalness:.12,clearcoat:.9});for(const side of [-1,1]){const rail=new THREE.Mesh(new RoundedBoxGeometry(.14,12.4,.45,4,.064),railMaterial);rail.position.set(side*5.13,6.17,-.04);rail.castShadow=true;this.scene.add(rail);const glass=new THREE.Mesh(new THREE.PlaneGeometry(.17,12),new THREE.MeshBasicMaterial({color:'#fffdf0',transparent:true,opacity:.64,depthWrite:false}));glass.position.set(side*5.09,6.1,.23);this.scene.add(glass);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(.22,12),new THREE.MeshBasicMaterial({color:'#768468',transparent:true,opacity:.08,depthWrite:false}));shadow.position.set(side*4.96,6.02,-2.5);this.scene.add(shadow);}
  const lip=new THREE.Mesh(new RoundedBoxGeometry(10.55,.15,.1,3,.07),new THREE.MeshPhysicalMaterial({color:'#f5f4e7',transparent:true,opacity:.55,roughness:.14,clearcoat:1,depthWrite:false}));lip.position.set(0,.03,2.29);this.scene.add(lip);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.ShadowMaterial({color:'#556746',opacity:.13}));floor.rotation.x=-Math.PI/2;floor.position.y=-.48;floor.receiveShadow=true;this.scene.add(floor);
  const marks=[];for(let x=-4.8;x<=4.8;x+=.43)marks.push(x,DANGER_Y,.12,x+.2,DANGER_Y,.12);const lineGeo=new THREE.BufferGeometry();lineGeo.setAttribute('position',new THREE.Float32BufferAttribute(marks,3));this.dangerLine=new THREE.LineSegments(lineGeo,new THREE.LineBasicMaterial({color:'#9da18b',transparent:true,opacity:.46}));this.scene.add(this.dangerLine);
  const guideGeo=new THREE.BufferGeometry();guideGeo.setAttribute('position',new THREE.Float32BufferAttribute([0,1,0,0,12.8,0],3));this.aimGuide=new THREE.Line(guideGeo,new THREE.LineDashedMaterial({color:'#77945d',transparent:true,opacity:.36,dashSize:.16,gapSize:.18}));this.aimGuide.computeLineDistances();this.scene.add(this.aimGuide);
  this.landingRing=new THREE.Mesh(new THREE.RingGeometry(.2,.235,40),new THREE.MeshBasicMaterial({color:'#75975a',transparent:true,opacity:.4,side:THREE.DoubleSide,depthWrite:false}));this.landingRing.position.z=-2.44;this.scene.add(this.landingRing);
 }
 _createMaterial(level){
  const skin=this._skinTexture(level),rough=level===8?.28:level===9?.31:.22;const material=new THREE.MeshPhysicalMaterial({color:COLORS[level],map:skin,roughness:rough,metalness:0,clearcoat:1,clearcoatRoughness:.10,transmission:level===8||level===9?.12:.25,thickness:.75,ior:1.38,attenuationColor:COLORS[level],attenuationDistance:3.0,envMapIntensity:1.0});material.userData.level=level;return material;
 }
 _skinTexture(level){
  const canvas=document.createElement('canvas');canvas.width=384;canvas.height=256;const c=canvas.getContext('2d');c.fillStyle='#ffffff';c.fillRect(0,0,384,256);let seed=level*97+31;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  // Fruit flesh has a fine, deep texture. None of these maps is fetched from a network.
  for(let i=0;i<(level===8?1100:1400);i++){const x=random()*384,y=random()*256,r=.35+random()*1.35;c.fillStyle=level===3||level===4?'rgba(112,70,6,.18)':'rgba(110,64,34,.05)';c.beginPath();c.ellipse(x,y,r,r*(.6+random()*.6),0,0,TAU);c.fill();}
  if(level===7){const g=c.createLinearGradient(0,0,384,0);g.addColorStop(0,'#ffdaac');g.addColorStop(.48,'#ffffff');g.addColorStop(.72,'#fcb8bd');g.addColorStop(1,'#ffd4a7');c.fillStyle=g;c.globalAlpha=.4;c.fillRect(0,0,384,256);c.globalAlpha=1;}
  if(level===8){c.strokeStyle='#8b6510';c.lineWidth=1.6;c.globalAlpha=.6;for(let i=-256;i<640;i+=28){c.beginPath();c.moveTo(i,0);c.lineTo(i+256,256);c.stroke();c.beginPath();c.moveTo(i+256,0);c.lineTo(i,256);c.stroke();}c.globalAlpha=1;}
  if(level===9){c.strokeStyle='rgba(213,224,153,.5)';c.lineWidth=1.25;for(let i=0;i<800;i++){const x=random()*384,y=random()*256;c.beginPath();c.moveTo(x,y);c.lineTo(x+random()*14-7,y+random()*12-6);c.stroke();}}
  const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=4;return texture;
 }
 _leafGeometry(){
  const p=[],uv=[];const segments=7;for(let i=0;i<segments;i++){const t0=i/segments,t1=(i+1)/segments;for(const side of [-1,1]){const w0=Math.sin(t0*Math.PI)*.23,w1=Math.sin(t1*Math.PI)*.23,y0=t0,y1=t1,z0=Math.sin(t0*Math.PI)*.12,z1=Math.sin(t1*Math.PI)*.12;p.push(0,y0,z0,side*w0,y0,z0-.04,side*w1,y1,z1-.04,0,y0,z0,side*w1,y1,z1-.04,0,y1,z1);uv.push(.5,t0,(side+1)/2,t0,(side+1)/2,t1,.5,t0,(side+1)/2,t1,.5,t1);}}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(p,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geometry.computeVertexNormals();return geometry;
 }
 _shape(level,x,y,z){
  let sx=1,sy=1,sz=.9;
  if(level===0){sx=.98;sy=.96;}
  if(level===1){sx=.84+.15*ease(clamp((y+.82)/1.5,0,1));sy=.99;sz=.86;}
  if(level===2){sx=.99;sy=.96;sz=.98;}
  if(level===3){sx=1.06;sy=.86;sz=.86;}
  if(level===4){sy=.94;sz=.95;}
  if(level===5){const notch=Math.exp(-(x*x+z*z)*13)*.1;sx=.99;sy=1-notch;sz=.96;}
  if(level===6){sx=.8-.25*ease(clamp((y+.1)/1.1,0,1));sx+=.18*Math.exp(-Math.pow((y+.34)*1.8,2));sy=1.02;sz=sx;}
  if(level===7){sx=.97;sy=.94;sz=.85;const seam=Math.exp(-x*x*30)*.046;x*=1-seam;z*=1-seam;}
  if(level===8){sx=.94;sy=1.0;sz=.85;}
  if(level===9){sx=.99;sy=.97;sz=.91;}
  if(level===10){sx=1.0;sy=.95;sz=.85;}
  return new THREE.Vector3(x*sx,y*sy,z*sz);
 }
 _createVisual(body,preview=false){
  const {id,level,radius}=body,group=new THREE.Group();const geometry=new THREE.SphereGeometry(1,34,22);const original=geometry.attributes.position.array.slice(),normals=geometry.attributes.normal.array.slice();const shaped=new Float32Array(original.length);for(let i=0;i<original.length;i+=3){const p=this._shape(level,original[i],original[i+1],original[i+2]);shaped[i]=p.x;shaped[i+1]=p.y;shaped[i+2]=p.z;}geometry.attributes.position.array.set(shaped);geometry.computeVertexNormals();geometry.attributes.position.setUsage(THREE.DynamicDrawUsage);geometry.attributes.normal.setUsage(THREE.DynamicDrawUsage);
  const mesh=new THREE.Mesh(geometry,this.materials[level]);mesh.castShadow=!preview;mesh.receiveShadow=true;group.add(mesh);
  const visual={id,level,radius,group,mesh,geometry,original:shaped,normals,bindings:[],dents:Array.from({length:8},(_,i)=>({angle:i/8*TAU,value:0,velocity:0,target:0})),wobble:0,wobbleV:0,angle:body.angle||0,formed:false,bornAt:this.time,position:new THREE.Vector3(body.x-WIDTH/2,body.y,0),preview};group.scale.setScalar(radius);group.position.copy(visual.position);this.scene.add(group);
  this._decorate(visual);if(!preview)this.visuals.set(id,visual);return visual;
 }
 _bind(visual,mesh,direction,offset=0,scale=.1){const d=direction.clone().normalize(),p=this._shape(visual.level,d.x,d.y,d.z);mesh.position.copy(p).addScaledVector(d,offset);mesh.scale.setScalar(scale);visual.group.add(mesh);visual.bindings.push({mesh,direction:d,offset,scale,originalRotation:mesh.quaternion.clone()});return mesh;}
 _decorate(v){
  const level=v.level;if(level!==3&&level!==9&&level!==10){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,0,0),new THREE.Vector3(.025,.1,.008),new THREE.Vector3(.07,.22,-.01)]);const stem=new THREE.Mesh(new THREE.TubeGeometry(curve,7,.024,5,false),this.stemMaterial);this._bind(v,stem,new THREE.Vector3(0,1,0),-.015,level===0?1.25:.7);}
  if(level===1){for(let i=0;i<5;i++){const leaf=new THREE.Mesh(this.leafGeometry,this.leafMaterial);leaf.rotation.z=i/5*TAU;leaf.rotation.x=1.25;this._bind(v,leaf,new THREE.Vector3(Math.sin(i/5*TAU)*.18,.97,Math.cos(i/5*TAU)*.18),-.02,.42);}}
  else if(level===8){for(let i=0;i<7;i++){const leaf=new THREE.Mesh(this.leafGeometry,this.leafMaterial);leaf.rotation.z=(i-3)*.22;leaf.rotation.y=(i%2?1:-1)*.22;leaf.rotation.x=(i%3-1)*.35;this._bind(v,leaf,new THREE.Vector3((i-3)*.035,1,0),-.03,.47+(i%3)*.13);}}
  else if([0,2,4,5,6,7].includes(level)){const leaf=new THREE.Mesh(this.leafGeometry,this.leafMaterial);leaf.rotation.z=-1.15;leaf.rotation.x=-.32;this._bind(v,leaf,new THREE.Vector3(.02,.98,.07),.04,level===0?.43:.34);}
  const count=level===1?26:level===10?13:0;if(count){const seedMesh=new THREE.InstancedMesh(this.seedGeometry,level===10?this.darkSeedMaterial:this.seedMaterial,count);seedMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);seedMesh.castShadow=false;v.group.add(seedMesh);v.seeds={mesh:seedMesh,points:[],matrix:new THREE.Matrix4()};for(let i=0;i<count;i++){let x,y,z;if(level===10){const angle=i*2.39996,rr=.32+((i*7)%13)/13*.45;x=Math.cos(angle)*rr;y=Math.sin(angle)*rr;z=Math.sqrt(1-x*x-y*y);}else{const y0=1-(i+.5)/count*2,a=i*2.39996;x=Math.sqrt(1-y0*y0)*Math.cos(a);y=y0;z=Math.sqrt(1-y0*y0)*Math.sin(a);}v.seeds.points.push({d:new THREE.Vector3(x,y,z),rotation:new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,1),new THREE.Vector3(x,y,z).normalize()),scale:new THREE.Vector3(level===10?.03:.018,level===10?.052:.035,.014)});}}
  const bubbles=new THREE.InstancedMesh(this.bubbleGeometry,this.bubbleMaterial,5);bubbles.instanceMatrix.setUsage(THREE.DynamicDrawUsage);v.group.add(bubbles);v.bubbles={mesh:bubbles,points:Array.from({length:5},(_,i)=>{const a=(i+v.level*.37)*2.399;return {p:new THREE.Vector3(Math.cos(a)*(.25+i*.085),Math.sin(a)*(.26+i*.065),.45+i*.05),size:.015+(i%3)*.012};}),matrix:new THREE.Matrix4()};
  if(level===10)this._watermelonRind(v);
  if(level===7){const points=[];for(let i=0;i<=24;i++){const a=-1.16+i/24*2.28,d=new THREE.Vector3(0,Math.sin(a),Math.cos(a));points.push(this._shape(level,d.x,d.y,d.z).addScaledVector(d,.010));}const seam=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#b84451',transparent:true,opacity:.42}));v.group.add(seam);v.seam=seam;v.seamOriginal=seam.geometry.attributes.position.array.slice();}
 }
 _watermelonRind(v){
  // A cut-away dome: the back is striped skin, the front is translucent seeded red flesh.
  const canvas=document.createElement('canvas');canvas.width=512;canvas.height=256;const c=canvas.getContext('2d');c.fillStyle='#43934b';c.fillRect(0,0,512,256);for(let stripe=0;stripe<10;stripe++){c.fillStyle=stripe%2?'#246a39':'#679e44';c.beginPath();const start=stripe*51;for(let y=0;y<=256;y+=8)c.lineTo(start+Math.sin(y*.065+stripe)*5,y);for(let y=256;y>=0;y-=8)c.lineTo(start+22+Math.sin(y*.063+stripe)*5,y);c.closePath();c.fill();}for(let i=0;i<700;i++){c.fillStyle=i%2?'#7ea950':'#315b31';c.globalAlpha=.18;c.fillRect((i*79)%512,(i*113)%256,2,1);}c.globalAlpha=1;const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;
  // The opening is exactly a circle, not a jagged set of discarded triangles.
  const cutTheta=Math.acos(.50/1.045),g=new THREE.SphereGeometry(1.045,56,30,0,TAU,cutTheta,Math.PI-cutTheta);g.rotateX(Math.PI/2);const base=g.attributes.position.array.slice();for(let i=0;i<base.length;i+=3){const p=this._shape(10,base[i],base[i+1],base[i+2]);base[i]=p.x;base[i+1]=p.y;base[i+2]=p.z;}g.attributes.position.array.set(base);g.computeVertexNormals();const material=new THREE.MeshPhysicalMaterial({map:texture,color:'#b6cf91',roughness:.29,clearcoat:.9,clearcoatRoughness:.12,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,material);mesh.castShadow=true;v.group.add(mesh);v.rind={geometry:g,original:base};
  const ring=new THREE.Mesh(new THREE.RingGeometry(.861,.920,72,2),new THREE.MeshPhysicalMaterial({color:'#d2dfa2',roughness:.3,clearcoat:.7,side:THREE.DoubleSide}));const ringP=ring.geometry.attributes.position.array;for(let i=0;i<ringP.length;i+=3){ringP[i+1]*=.95;ringP[i+2]+=.435;}ring.geometry.computeVertexNormals();v.group.add(ring);v.rindRing={mesh:ring,original:ringP.slice()};
 }
 _createPreview(){const visual=this._createVisual({id:'preview',level:0,radius:FRUITS[0].radius,x:5,y:13.2},true);visual.kick=0;return visual;}
 _syncVisuals(){
  if(!this.renderer||this.renderError)return;const m=this.model,wanted=new Set();let bodies=m.bodies||[];
  if(m.status==='ready')bodies=[{id:'demo-0',level:7,x:1.55,y:1.48,radius:FRUITS[7].radius,angle:.12},{id:'demo-1',level:4,x:4.1,y:.84,radius:FRUITS[4].radius,angle:-.2},{id:'demo-2',level:6,x:6.15,y:1.25,radius:FRUITS[6].radius,angle:-.25},{id:'demo-3',level:1,x:8.12,y:.43,radius:FRUITS[1].radius,angle:.25},{id:'demo-4',level:2,x:8.9,y:.54,radius:FRUITS[2].radius,angle:-.2},{id:'demo-5',level:3,x:3.6,y:2.2,radius:FRUITS[3].radius,angle:.44},{id:'demo-6',level:0,x:4.7,y:2.7,radius:FRUITS[0].radius,angle:.1}];
  for(const body of bodies){wanted.add(body.id);const v=this.visuals.get(body.id)||this._createVisual(body);v.target=body;v.angle=body.angle||0;}
  for(const [id,v] of this.visuals)if(!wanted.has(id)){this._disposeVisual(v);this.visuals.delete(id);}
  if(this.preview.level!==m.currentLevel){this._disposeVisual(this.preview);this.preview=this._createVisual({id:'preview',level:m.currentLevel||0,radius:FRUITS[m.currentLevel||0].radius,x:m.aimX||5,y:13.2},true);this.preview.kick=.15;}
  this.preview.group.visible=m.status!=='over';const aim=m.aimX??5;const spawnY=HEIGHT-FRUITS[m.currentLevel||0].radius-.08;this.preview.target={x:aim,y:spawnY+Math.sin(this.time*2)*.035,angle:Math.sin(this.time*1.8)*.035,contacts:[]};
  let landing=FRUITS[m.currentLevel||0].radius;const radius=FRUITS[m.currentLevel||0].radius;for(const b of m.bodies||[]){const dx=b.x-aim,sum=radius+b.radius;if(Math.abs(dx)<sum)landing=Math.max(landing,b.y+Math.sqrt(sum*sum-dx*dx));}landing=Math.min(landing,12.95);this.aimGuide.visible=m.status==='playing';this.landingRing.visible=m.status==='playing';if(this.aimGuide.visible){const p=this.aimGuide.geometry.attributes.position;p.setXYZ(0,aim-5,landing,-.5);p.setXYZ(1,aim-5,spawnY-radius*.9,-.5);p.needsUpdate=true;this.aimGuide.computeLineDistances();this.landingRing.position.set(aim-5,landing,-2.42);this.landingRing.scale.setScalar(radius*1.05);}
 }
 _deform(v,p){return this._deformXYZ(v,p.x,p.y,p.z,new THREE.Vector3());}
 _deformXYZ(v,x,y,z,out){
  const length=Math.sqrt(x*x+y*y+z*z)||1,nx=x/length,ny=y/length;let total=0,compression=0;for(const d of v.dents){if(Math.abs(d.value)<.0001)continue;const cosine=nx*Math.cos(d.angle)+ny*Math.sin(d.angle);const weight=Math.exp((cosine-1)*7);compression+=d.value*weight;total+=d.value;}
  const bulge=total*.085,w=v.wobble,radial=1+bulge+w*(nx*ny*.6+(ny*ny-.33)*.20);x*=radial;y*=radial;z*=1+bulge-w*.10;const divisor=Math.max(.35,Math.sqrt(nx*nx+ny*ny));x-=nx/divisor*compression;y-=ny/divisor*compression;return out.set(x,y,z);
 }
 _deformVisual(v,dt){
  const target=v.target||{x:v.position.x+5,y:v.position.y,contacts:[]};v.group.rotation.z=v.angle;
  for(const d of v.dents)d.target=0;for(const contact of target.contacts||[]){const a=Math.atan2(-contact.ny,-contact.nx)-v.angle;for(const d of v.dents){const weight=Math.exp((Math.cos(d.angle-a)-1)*9),load=clamp(.035+(contact.depth||contact.penetration||0)/v.radius*.65+(contact.impulse||0)/(v.radius*v.radius*45),.025,.20);d.target=Math.max(d.target,load*weight);}}
  const steps=Math.max(1,Math.ceil(dt/.012)),step=dt/steps;if(dt>0){for(let n=0;n<steps;n++){for(const d of v.dents){d.velocity+=((d.target-d.value)*145-d.velocity*11)*step;d.value=clamp(d.value+d.velocity*step,-.065,.30);}v.wobbleV+=(-105*v.wobble-v.wobbleV*8.4)*step;v.wobble=clamp(v.wobble+v.wobbleV*step,-.16,.16);}}
  if(this.reducedMotion){v.wobble=0;for(const d of v.dents)d.value=d.target;}
  const deformation=[...v.dents.map(d=>d.value),v.wobble];const changed=!v.lastDeformation||deformation.some((value,index)=>Math.abs(value-v.lastDeformation[index])>.00022);
  if(changed){
   v.lastDeformation=deformation;const p=v.geometry.attributes.position.array;let displacement=0;
   for(let i=0;i<p.length;i+=3){const point=this._deformXYZ(v,v.original[i],v.original[i+1],v.original[i+2],this._deformPoint);p[i]=point.x;p[i+1]=point.y;p[i+2]=point.z;const dx=point.x-v.original[i],dy=point.y-v.original[i+1],dz=point.z-v.original[i+2];displacement=Math.max(displacement,dx*dx+dy*dy+dz*dz);}
   v.maxVertexDisplacement=Math.sqrt(displacement);this._maxIndent=Math.max(this._maxIndent,v.maxVertexDisplacement);v.geometry.attributes.position.needsUpdate=true;v.geometry.computeVertexNormals();
   for(const part of [v.rind,v.rindRing&&{geometry:v.rindRing.mesh.geometry,original:v.rindRing.original},v.seam&&{geometry:v.seam.geometry,original:v.seamOriginal}])if(part){const p=part.geometry.attributes.position.array;for(let i=0;i<p.length;i+=3){const point=this._deformXYZ(v,part.original[i],part.original[i+1],part.original[i+2],this._deformPoint);p[i]=point.x;p[i+1]=point.y;p[i+2]=point.z;}part.geometry.attributes.position.needsUpdate=true;if(part.geometry.index)part.geometry.computeVertexNormals();}
   for(const b of v.bindings){const base=this._shape(v.level,b.direction.x,b.direction.y,b.direction.z),position=this._deform(v,base).addScaledVector(b.direction,b.offset);b.mesh.position.copy(position);}
   if(v.seeds){const matrix=v.seeds.matrix;for(let i=0;i<v.seeds.points.length;i++){const seed=v.seeds.points[i],p=this._deform(v,this._shape(v.level,seed.d.x,seed.d.y,seed.d.z)).addScaledVector(seed.d,.01);matrix.compose(p,seed.rotation,seed.scale);v.seeds.mesh.setMatrixAt(i,matrix);}v.seeds.mesh.instanceMatrix.needsUpdate=true;}
   if(v.bubbles){const matrix=v.bubbles.matrix;for(let i=0;i<v.bubbles.points.length;i++){const b=v.bubbles.points[i],p=this._deform(v,b.p);matrix.compose(p,new THREE.Quaternion(),new THREE.Vector3(b.size,b.size,b.size));v.bubbles.mesh.setMatrixAt(i,matrix);}v.bubbles.mesh.instanceMatrix.needsUpdate=true;}
  }
  if(v.formed){const age=this.time-v.bornAt,amount=age<.18?lerp(.28,.82,ease(age/.18)):1+Math.sin((age-.18)*20)*Math.exp(-(age-.18)*7)*.11;v.group.scale.setScalar(v.radius*amount);if(age>1)v.formed=false;}else v.group.scale.setScalar(v.radius);
  if(v.preview){v.position.x=lerp(v.position.x,target.x-5,1-Math.exp(-18*dt));v.position.y=target.y;v.kick=Math.max(0,(v.kick||0)-dt*.65);v.group.scale.set(v.radius*(1+v.kick*.25),v.radius*(1-v.kick*.4),v.radius);v.group.rotation.z=target.angle||0;v.group.position.copy(v.position);}else if(!v.fusing){v.position.set(target.x-5,target.y,0);v.group.position.copy(v.position);}
 }
 _burst(body,celebrate=false){
  if(!this.renderer||this.reducedMotion)return;const count=celebrate?42:8;for(let i=0;i<count&&this.particles.length<180;i++){const angle=i*2.3999,material=new THREE.MeshPhysicalMaterial({color:celebrate?['#f3ce56','#c1d760','#ef7289','#fff2c5'][i%4]:COLORS[body.level],roughness:.25,clearcoat:1,transparent:true,opacity:.85,depthWrite:false}),mesh=new THREE.Mesh(this.bubbleGeometry,material);mesh.position.set(body.x-5,body.y,.6);this.scene.add(mesh);this.particles.push({mesh,velocity:new THREE.Vector3(Math.cos(angle)*(1.3+i%4),Math.sin(angle)*(1.8+i%3)+2.4,1+i%2),life:celebrate?1.7:.55,age:0,size:celebrate?.045+i%3*.025:.035+i%3*.022});}
 }
 _disposeVisual(v){this.scene?.remove(v.group);v.geometry.dispose();if(v.rind){v.rind.geometry.dispose();v.group.children.find(child=>child.geometry===v.rind.geometry)?.material.map?.dispose();v.group.children.find(child=>child.geometry===v.rind.geometry)?.material.dispose();}for(const child of v.group.children){if(child.geometry!==v.geometry&&child.geometry!==this.leafGeometry&&child.geometry!==this.seedGeometry&&child.geometry!==this.bubbleGeometry&&child.geometry!==v.rind?.geometry)child.geometry?.dispose();if(child.isInstancedMesh)child.dispose();} }
 _clearVisuals(){for(const v of this.visuals.values())this._disposeVisual(v);this.visuals.clear();for(const f of this.fusions)this._disposeVisual(f.visual);this.fusions.length=0;for(const p of this.particles){this.scene?.remove(p.mesh);p.mesh.material.dispose();}this.particles.length=0;this._maxIndent=0;}
 _renderFrame(dt){
  if(!this.renderer||this.renderError||!this._visible)return;this.time+=dt;for(const v of this.visuals.values())this._deformVisual(v,dt);if(this.preview)this._deformVisual(this.preview,dt);
  for(let i=this.fusions.length-1;i>=0;i--){const f=this.fusions[i];f.age+=dt;const t=clamp(f.age/f.life,0,1);if(t>=1){this._disposeVisual(f.visual);this.fusions.splice(i,1);continue;}f.visual.fusing=true;f.visual.target={contacts:[]};this._deformVisual(f.visual,dt);f.visual.group.position.lerpVectors(f.from,f.to,ease(t));f.visual.group.scale.setScalar(f.visual.radius*(1-.76*ease(t)));f.visual.group.rotation.z+=Math.sin(t*Math.PI)*.15;}
  for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.age+=dt;if(p.age>=p.life){this.scene.remove(p.mesh);p.mesh.material.dispose();this.particles.splice(i,1);continue;}p.velocity.y-=8*dt;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.rotation.z+=dt*2;p.mesh.scale.setScalar(p.size*(1-p.age/p.life));p.mesh.material.opacity=.8*(1-p.age/p.life);}
  const danger=this.root.classList.contains('fm-in-danger');this.dangerLine.material.color.set(danger?'#d77355':'#9da18b');this.dangerLine.material.opacity=danger?.65+Math.sin(this.time*7)*.24:.40;if(this._toastUntil&&this.time>this._toastUntil){this.root.querySelector('#fm-merge-toast').classList.remove('show');this._toastUntil=0;}
  this.renderer.render(this.scene,this.camera);this.frames++;
 }
}
export default FruitMergeGame;
